# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'WalkyCam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WalkyCam
  pod 'MapboxMaps', '11.3.0'
  pod 'DJI-SDK-iOS'
  pod 'DJI-UXSDK-iOS'
  pod 'DJIWidget'
end
