# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'WalkyCam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WalkyCam
  pod 'JitsiMeetSDK'
  pod 'MapboxMaps', '11.3.0'

end
