# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'WalkyCam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WalkyCam
  pod 'JitsiMeetSDK'
  pod 'MapboxMaps', '11.1.0'
  
  target 'WalkyCamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WalkyCamUITests' do
    # Pods for testing
  end

end
