import SwiftUI

protocol FunctionsRouterProtocol: Router {
    func routeToVideoCall()
    func routeToWalkCamer()
    func routeToARHands()
    func routeToDrone()
    func routeToScan3D()
    func routeToCryptoWallet()
    func routeToIOT()
    func routeTo3DPrinting()
    func routeToAI()
    func routeToNFT()
    func routeToDigitalTwins()
    func routeToLidar()
    func routeToGames()
    func routeToPlayBusiness()

    func routeToRadar()
    func routeToROV()
    func routeToScreenAd()
    func routeToDrugTest()
    func routeToRobot()
    func routeToCamera360()
    func routeToConsulting()
    func routeToCRM()
    func routeToDetectorMetales()
    func routeToEcografia()
    func routeToLawConsulting()
    func routeToThermalCamera()
    func routeToCertifiedRecording()
    func routeToRuralDrone()
    
    func routeToRegistrationPlans()
    func routeToTelepresenciaSuperbanner()
    func routeToDogRobotSuperbanner()
    func routeToMascotSuperbanner()
    func routeToGeoradarSuperbanner()
    func routeToDetectorSuperbanner()
    func routeToAnalysisSuperbanner()
}
